#!/bin/bash
set -e

if echo "$-" | grep -q "i"; then
    # Don't do anything when the shell is running in interactive mode.
    echo "This script don't do anything in running interactive mode."
    return
fi

WORK_DIR="$HOME"
DOT_DIR="$HOME/dotfiles-master"
DOT_TARBALL="dotfiles.tar.gz"
REMOTE_TAR_URL="https://github.com/hiro0412/dotfiles/archive/master.tar.gz"

die(){
    echo "oops!"
    exit 1
}

if [ ! -d "${DOT_DIR}" ];
then
    cd "$WORK_DIR" || die
    echo "download from tarball from : $REMOTE_TAR_URL"
    curl -s -L "$REMOTE_TAR_URL" -o "$DOT_TARBALL" || die
    echo "done."

    echo -n "extracting.."
    tar xzf "$DOT_TARBALL" || die
    echo " done."
     
    cd "$DOT_DIR" || die
fi

dotfiles_install(){
    echo "dotfiles_install"
}

dotfiles_deploy(){
    echo "dotfiles_deploy"
}

dotfiles_install || die
dotfiles_deploy || die

    
    
